Vagrant.configure("2") do |config|
	config.vm.box = "generic/ubuntu2204"
	config.vm.provider :virtualbox do |v|
		v.memory = 1024
		v.cpus = 1
	end
	
	boxes = [
		{ :name => "web",
		  :ip => "192.168.56.10",
		},
		{ :name => "log-nginx",
		  :ip => "192.168.56.11",
		},
		{ :name => "log-all",
		  :ip => "192.168.56.12",
		}
	]
	
	boxes.each do |opts|
		config.vm.define opts[:name] do |config|
			config.vm.hostname = opts[:name]
			config.vm.network "private_network", ip: opts[:ip]
			config.ssh.host = "127.0.0.1"
			config.ssh.connect_timeout = 5
		end
	end
end

