- name: Установить openssl
  apt:
    name: openssl
    state: present

- name: Создать директорию для SSL
  file:
    path: /etc/apache2/ssl
    state: directory
    mode: '0755'

- name: Сгенерировать самоподписанный сертификат
  command: >
    openssl req -x509 -nodes -days 365
    -newkey rsa:2048
    -keyout /etc/apache2/ssl/apache-selfsigned.key
    -out /etc/apache2/ssl/apache-selfsigned.crt
    -subj "/C=RU/ST=Moscow/L=Moscow/O=Example/CN=localhost"
  args:
    creates: /etc/apache2/ssl/apache-selfsigned.crt

- name: Включить модуль ssl
  command: a2enmod ssl
  notify: Restart Apache

- name: Включить конфигурацию ssl
  command: a2ensite default-ssl
  notify: Restart Apache
