- name: Устанавливаем rsyslog на сервер
  apt:
    name: rsyslog
    state: present
  become: true

- name: Включаем прием логов по UDP
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^#?\$ModLoad imudp'
    line: '$ModLoad imudp'
  become: true

- name: Включаем порт 514 UDP
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^#?\$UDPServerRun'
    line: '$UDPServerRun 514'
  become: true

- name: Создаем отдельный файл для логов клиентов
  copy:
    dest: /etc/rsyslog.d/10-client-logs.conf
    content: |
      if $fromhost-ip != '127.0.0.1' then /var/log/client_logs.log
      & stop
  become: true

- name: Открываем порт 514 через shell (без коллекций)
  become: true
  shell: |
    ufw allow 514/udp
    ufw reload

- name: Перезапускаем rsyslog
  service:
    name: rsyslog
    state: restarted
  become: true
