- name: restart prometheus
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes

- name: restart node_exporter
  become: true
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    
- name: restart alertmanager
  systemd:
    name: alertmanager
    state: restarted
    daemon_reload: true

- name: daemon reload
  systemd:
    daemon_reload: yes
