Vagrant.configure("2") do |config|
  config.vm.define "web1" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "web1"
    web.vm.network "private_network", ip: "192.168.56.10"
  end
  config.vm.define "mail1" do |mail|
    mail.vm.box = "ubuntu/focal64"
    mail.vm.hostname = "mail1"
    mail.vm.network "private_network", ip: "192.168.56.11"
  end
  config.vm.define "mon1" do |mon|
    mon.vm.box = "ubuntu/focal64"
    mon.vm.hostname = "mon1"
    mon.vm.network "private_network", ip: "192.168.56.12"
    mon.vm.network "forwarded_port", guest: 9090, host: 9090
  end
  config.vm.define "db1" do |db1|
    db1.vm.box = "ubuntu/focal64"
    db1.vm.hostname = "db1"
    db1.vm.network "private_network", ip: "192.168.56.13"
  end
  config.vm.define "db2" do |db2|
    db2.vm.box = "ubuntu/focal64"
    db2.vm.hostname = "db2"
    db2.vm.network "private_network", ip: "192.168.56.14"
  end
end
