- name: Настройка ZFS и тестирование сжатия
  hosts: zfs
  become: true
  tasks:
    - name: Установка утилит ZFS
      apt:
        name: zfsutils-linux
        state: present
        update_cache: yes

    - name: Создание пула otus1 (RAID1)
      command: zpool create otus1 mirror /dev/sdb /dev/sdc
      ignore_errors: true

    - name: Создание пула otus2 (RAID1)
      command: zpool create otus2 mirror /dev/sdd /dev/sde
      ignore_errors: true

    - name: Создание пула otus3 (RAID1)
      command: zpool create otus3 mirror /dev/sdf /dev/sdg
      ignore_errors: true

    - name: Создание пула otus4 (RAID1)
      command: zpool create otus4 mirror /dev/sdh /dev/sdi
      ignore_errors: true

    - name: Установка сжатия lzjb на otus1
      command: zfs set compression=lzjb otus1
      ignore_errors: true

    - name: Установка сжатия lz4 на otus2
      command: zfs set compression=lz4 otus2
      ignore_errors: true

    - name: Установка сжатия gzip-9 на otus3
      command: zfs set compression=gzip-9 otus3
      ignore_errors: true

    - name: Установка сжатия zle на otus4
      command: zfs set compression=zle otus4
      ignore_errors: true

    - name: Скачивание файла в каждый пул
      shell: wget -P /otus{{ item }} https://gutenberg.org/cache/epub/2600/pg2600.converter.log
      with_items:
        - 1
        - 2
        - 3
        - 4
      ignore_errors: true