- name: Install base packages
  become: true
  apt:
    name: [vim, wget, curl, rsyslog]
    state: present
    update_cache: yes
- name: Install Apache and PHP
  become: true
  apt:
    name:
      - apache2
      - php
    state: present
    update_cache: yes
- name: Install msmtp
  become: true
  apt:
    name: msmtp
    state: present

- name: Copy form files
  copy:
    src: files/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0644'
  when: inventory_hostname == 'web1'
  
- name: Copy sendmail.php only to web1
  copy:
    src: sendmail.php
    dest: /var/www/html/sendmail.php
    owner: www-data
    group: www-data
    mode: '0644'
  when: inventory_hostname == 'web1'
  become: true

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: yes
